project:
  type: book
  output-dir: "docs"

lang: es
language:
  es:
    title-block-published: "Últ. actualización"

book:
  title: "Análisis Estadístico (UA)"
  author: 
    - Joaquín Bermejo
    - Victorio Costa
  date: "8/10/2024"
  chapters:
    - index.qmd
    - 0_conteo.qmd
    - 1_prob.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: false
    theme: cosmo
    css: style.css
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual

output:
  html_document:
    css: style.css
    citation_package: biblatex
